version: 0.1
phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
  build:
    commands:
      - cargo build --release

artifacts:
  files:
    - target/release/PRKSChingService
  discard-paths: "yes"

cache:
  paths:
    - $HOME/.cargo/registry/**/*